---
title: "Class 5: Visualization"
author: "C.K"
format: pdf
---

# Plotting in R

```{r}
plot(cars)
```

```{r}
library(ggplot2)
ggplot(cars)
#install.packages("ggplot2")
```

#ggPlot ggplot(input data)+aesthetics() +geom_point() geom_smoot() put a line through it

```{r}

ggplot(data=cars)+aes(x=speed,y=dist)+geom_point()+geom_smooth()
```

```{r}

```

```{r}
## different layers added on top of another
ggplot(cars) +
  aes(x=speed, y=dist) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE)
```

```{r}
#bb=ggplot(cars) +
  #aes(x=speed, y=dist)+geom_point()
bb=ggplot(cars,aes(x=speed, y=dist))+geom_point()
# lm is the linear model
bb+geom_smooth(method = "lm",se=FALSE)
```

```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
nrow(genes)
```

```{r}
colnames(genes)
ncol(genes)
```

```{r}
 table(genes$State)
 round( table(genes$State)/nrow(genes) * 100, 2 )
```

```{r}
## check the aesthetic parameters to have different size, shape, colors for each individual points
ggplot(genes) + 
    aes(x=Condition1, y=Condition2) +
    geom_point()+labs(title="Some Plot")
p <- ggplot(genes) + 
    aes(x=Condition1, y=Condition2, col=State) +
    geom_point()
p
```

```{r}
p + scale_colour_manual( values=c("blue","gray","red") )
```

```{r}

p + scale_colour_manual(values=c("blue","gray","red")) +
    labs(title="Gene Expresion Changes Upon Drug Treatment",
         x="Control (no drug) ",
         y="Drug Treatment")
```

```{r}
# File location online
url <- "https://raw.githubusercontent.com/jennybc/gapminder/master/inst/extdata/gapminder.tsv"

gapminder <- read.delim(url)

library(dplyr)

gapminder_2007 <- gapminder %>% filter(year==2007)
```

```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) +
  geom_point()
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) +
  geom_point(alpha=0.5)
```

```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.5)
ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, color = pop) +
  geom_point(alpha=0.8)
ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, size = pop) +
  geom_point(alpha=0.5)
ggplot(gapminder_2007) + 
  geom_point(aes(x = gdpPercap, y = lifeExp,
                 size = pop), alpha=0.5) + 
  scale_size_area(max_size = 10)

```

```{r}
gapminder_1957 <- gapminder %>% filter(year==1957)

ggplot(gapminder_1957) + 
  aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop) +
  geom_point(alpha=0.7) + 
  scale_size_area(max_size = 10) 

gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)

ggplot(gapminder_1957) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop), alpha=0.7) + 
  scale_size_area(max_size = 10) +
  facet_wrap(~year)
```
