---
title: "Class 6"
author: "Chan-yu Kuo"
date: "2023-01-26"
output: pdf_document
---

# Example input vectors to start with

```{r}
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)
which.min(student2)
student2[-which.min(student2)]
mean(student2[-which.min(student2)],na.rm=TRUE)
## which.min will provide an index where the minimun value is providied in the array. na.rm = True is remove the nan value within the mean function when computing the mean value


```

```{r}
## Q1 compute the average grade of the student input
Grade <- function(student) {
  ## assigning any of the Na to 0
  if (any(is.na(student))){
    student[is.na(student)]=0
  }
  ## remove one minimun value (such as 0)
  ## calcualte mean value 
  return(mean(student[-which.min(student)]))

}

```

```{r}
mean(na.omit(student2))
mean(student2, na.rm=TRUE)
Grade(student3)

```

```{r}
## Copying all the student values into here
data1 <- read.csv("/Users/chan-yukuo/Desktop/BIMM143/Lab6/student_homework.csv", row.names=1)
which.max(apply(data1,1,Grade))
results <- apply(data1,1,Grade)
###apply(X, MARGIN, FUN)
## Margin =1 means claulcate the maxtrix x in row
### Q2 94.5 student 18 have the highest score
```
```{r}
hw_Grade <- function(hw) {
  ## assigning any of the Na to 0
  if (any(is.na(hw))){
    hw[is.na(hw)]=0
  }
  ## remove one minimun value (such as 0)
  ## calcualte mean value 
  
  return(mean(hw))

}
```

```{r}

which.min(apply(data1,2,hw_Grade))
apply(data1,2,hw_Grade)
## Does not remove the lowest value of the whole hw.
## q3: hw2 is the hardest

```

```{r}

## Q4 Look at the correlation of each hw 
data1[is.na(data1)]=0
cor(results,data1$hw5)
apply(data1,2,cor,y=results)

## specifying the y input of the cor



