---
title: "HW6"
author: "Chan-yu Kuo"
date: "2023-01-30"
output: pdf_document
---

```{r}
## Question: Can you improve this code? 
df <- data.frame(a=1:10, b=seq(200,400,length=10),c=11:20,d=NA)
df$a <- (df$a - min(df$a)) / (max(df$a) - min(df$a))
df$b <- (df$b - min(df$a)) / (max(df$b) - min(df$b))
df$c <- (df$c - min(df$c)) / (max(df$c) - min(df$c))
df$d <- (df$d - min(df$d)) / (max(df$a) - min(df$d))
df$d
```

```{r}
first_question<- function(a,b,c,d) {
  return((a - min(b)) / (max(c) - min(d)))
}
df <- data.frame(a=1:10, b=seq(200,400,length=10),c=11:20,d=NA)
df$a <-first_question(df$a,df$a,df$a,df$a)
df$b <-first_question(df$b,df$a,df$b,df$b)
df$c <-first_question(df$c,df$c,df$c,df$c)
df$d <-first_question(df$d,df$d,df$a,df$d)


```

```{r}
#install.packages("bio3d")
```

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```
```{r}
second_question<- function(str1,str2,str3){
  vector = c(str1,str2,str3)
  for (individual_string in vector){
    s1 <- read.pdb(individual_string)
    s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
    s1.b <- s1.chainA$atom$b
    plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
  }
    
}

second_question("4AKE","1AKE","1E4Y")

```
```{r}
s1 <- read.pdb("4AKE")
str(s1)
## Q1 based on the output, the object is data.frame called atom (or PDB structure object)
```
```{r}
?trim.pdb()
## Q2 based on the output, trim.pdb() select a subset from the large PDB obejct, with specified parameters such as "helix", "sheet" etc. 
```
```{r}
plotb3(s3.b, typ="l", ylab="Bfactor")
?plotb3
## Q3: sse=Null would turn off the marginal black and grey rectangles. sse represent the secondary strcture 
```
```{r}
### Q4 use facet in ggplot2 to combine several plots into one. This way we can compare multiple protein side by side
```

```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
## rbind (combine rows into one)
## dist compute the distance between any two rows of the matrix
## hclust input a dissimilarity structure produced by dist. (Meaning, the clustering is based on the distance computed between two rows of factor) 
plot(hc)
## Based on Cluster Dendrogram, s2.b and s3.b have highest similarity with least distance in between. 
```
```{r}
## Question 6 

sixth_question<- function(protein_name,chain_name){
  kinase <- read.pdb(protein_name)
  kinase.chainA <- trim.pdb(kinase, chain=chain_name, elety="CA")
  kinase.b <- kinase.chainA$atom$b
  plotb3(kinase.b, sse=kinase.chainA, typ="l", ylab="Bfactor")
}
### The input of the function sixth_question are protein_name and chain_name. 
### The function will read the data base based on the given protein_name, trim the data based on the chain given, and plot out the bfactor across the whole sequence. Bfactor is the displacement from the mean position value. 
### The output of a function is to plot out a graph that shows the Bfactor across the residue of the protein sequence.
```
```{r}
## Example
sixth_question("4AKE","B")
```

